### ISSUE TITLE
intro-to-simulation - qm - ERROR - Failed to connect to QuantumMachines server.

### ISSUE THREAD

**Issue by shterenlikht** [qua-platform/qua-libs#152]
I assumed that this script can be run successfully with no actual HW.

What am I doing wrong?

```
$ python3 intro-to-simulation.py 
2022-08-02 14:37:18,120 - qm - ERROR - Failed to connect to QuantumMachines server. Tried connecting to localhost:9510,localhost:80
Traceback (most recent call last):
  File "/efs/shterenlikht/QM_integration/qua-libs/Tutorials/intro-to-simulation/intro-to-simulation.py", line 16, in <module>
    qmm = QuantumMachinesManager(qop_ip)
  File "/efs/shterenlikht/QM_integration/sdk_0.3.7/qm/QuantumMachinesManager.py", line 63, in __init__
    raise Exception(message)
Exception: Failed to connect to QuantumMachines server. Tried connecting to localhost:9510,localhost:80
```

**Comment by tomerfqm** [comment]
Hi @shterenlikht.

The simulation takes place on the actual hardware, requiring a connection to a Quantum Machines server.
Do you have an OPX or an OPX+?

**Comment by shterenlikht** [comment]
no, nothing. Sorry I misunderstood.

**Comment by yomach** [comment]
> no, nothing. Sorry I misunderstood.

Hi @shterenlikht,
No worries :)

The examples here also come with readme files that can demonstrate the behavior even without running it locally.

May I ask where you're from?

The simulator can also work on a remote server which we can open for existing and potential customers. If that might be relevant feel free to say so.

**Comment by shterenlikht** [comment]
I'm from ParTec. We are collaborating with QM. Please talk to @dorisraeli if you want to know more.

Not sure what you mean by a "remote server". If this is something I can pass to `QuantumMachinesManager()` to make it return some meaningful object, that would be very helpful.

**Comment by yomach** [comment]
Discussion continued over e-mail.
